import React from 'react';
import { LegalDocument, AttorneyBrief } from '../types/legal';
import { LegalAnalyzer } from '../services/legalAnalyzer';
import { FileText, Copy, Printer, Check, X, ShieldAlert, CheckCircle } from 'lucide-react';
import confetti from 'canvas-confetti';

interface AttorneyBriefModalProps {
  document: LegalDocument;
  isOpen: boolean;
  onClose: () => void;
}

export const AttorneyBriefModal: React.FC<AttorneyBriefModalProps> = ({
  document,
  isOpen,
  onClose,
}) => {
  if (!isOpen) return null;

  const [copied, setCopied] = React.useState(false);
  const brief: AttorneyBrief = LegalAnalyzer.generateAttorneyBrief(document, 'User / Client');

  const formatAsMarkdown = (): string => {
    return `# ATTORNEY CONSULTATION BRIEF
**Document**: ${brief.documentTitle}
**Date Prepared**: ${brief.generatedDate}
**Recommended Specialist**: ${brief.recommendedSpecialist}
**Complexity Assessment**: ${brief.estimatedComplexity}

---
## Executive Summary
${brief.executiveSummary}

---
## Flagged High-Priority Issues for Attorney Review
${brief.criticalRedFlags.map(f => `
### ${f.clauseRef}: ${f.title}
- **Primary Concern**: ${f.concern}
- **Questions for Legal Counsel**:
${f.questionsToAskLawyer.map(q => `  * ${q}`).join('\n')}
`).join('\n')}

---
## Recommended Meeting Checklist
${brief.checklistForMeeting.map(item => `- [ ] ${item}`).join('\n')}

---
*Generated by LexiGuard AI — Educational Legal Intelligence Platform.*
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(formatAsMarkdown());
    setCopied(true);
    confetti({
      particleCount: 40,
      spread: 60,
      origin: { y: 0.5 },
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="modal-backdrop" onClick={onClose} role="dialog" aria-modal="true" aria-labelledby="brief-title">
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="modal-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
            <FileText size={20} style={{ color: 'var(--accent-primary)' }} />
            <h3 id="brief-title" style={{ fontSize: '1.2rem', fontWeight: 800 }}>
              Attorney Consultation Brief
            </h3>
          </div>
          <button onClick={onClose} className="icon-btn" aria-label="Close dialog">
            <X size={16} />
          </button>
        </div>

        <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1.25rem' }}>
          This dossier organizes key red flags and targeted questions to bring to a licensed attorney. It ensures you maximize value and save billable hours during your consultation.
        </p>

        {/* Metadata summary */}
        <div style={{ background: 'var(--bg-tertiary)', padding: '1rem', borderRadius: 'var(--radius-md)', marginBottom: '1.5rem', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '0.75rem', fontSize: '0.85rem' }}>
          <div>
            <span style={{ color: 'var(--text-muted)', display: 'block', fontSize: '0.75rem' }}>DOCUMENT:</span>
            <strong>{brief.documentTitle}</strong>
          </div>
          <div>
            <span style={{ color: 'var(--text-muted)', display: 'block', fontSize: '0.75rem' }}>RECOMMENDED SPECIALIST:</span>
            <strong style={{ color: 'var(--accent-secondary)' }}>{brief.recommendedSpecialist}</strong>
          </div>
          <div>
            <span style={{ color: 'var(--text-muted)', display: 'block', fontSize: '0.75rem' }}>ESTIMATED COMPLEXITY:</span>
            <strong style={{ color: brief.estimatedComplexity === 'Complex' ? 'var(--risk-critical)' : 'var(--text-primary)' }}>
              {brief.estimatedComplexity}
            </strong>
          </div>
        </div>

        {/* Executive Summary */}
        <div style={{ marginBottom: '1.5rem' }}>
          <h4 style={{ fontSize: '0.95rem', fontWeight: 700, marginBottom: '0.4rem', color: 'var(--text-primary)' }}>
            Executive Briefing Summary:
          </h4>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            {brief.executiveSummary}
          </p>
        </div>

        {/* Flagged Issues & Questions to Ask */}
        <div style={{ marginBottom: '1.5rem' }}>
          <h4 style={{ fontSize: '0.95rem', fontWeight: 700, marginBottom: '0.75rem', color: 'var(--risk-critical)', display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
            <ShieldAlert size={16} /> Key Clauses & Targeted Questions for Your Lawyer:
          </h4>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
            {brief.criticalRedFlags.map((flag, idx) => (
              <div key={idx} style={{ background: 'rgba(0,0,0,0.25)', borderLeft: '3px solid var(--risk-critical)', padding: '0.85rem', borderRadius: 'var(--radius-sm)' }}>
                <strong style={{ fontSize: '0.9rem', display: 'block', marginBottom: '0.2rem' }}>
                  {flag.clauseRef}: {flag.title}
                </strong>
                <p style={{ fontSize: '0.83rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
                  {flag.concern}
                </p>

                <div style={{ fontSize: '0.8rem', color: 'var(--accent-secondary)' }}>
                  <strong>Questions to Ask:</strong>
                  <ul style={{ paddingLeft: '1.2rem', marginTop: '0.25rem' }}>
                    {flag.questionsToAskLawyer.map((q, qIdx) => (
                      <li key={qIdx} style={{ color: 'var(--text-primary)' }}>{q}</li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Checklist */}
        <div style={{ marginBottom: '1.5rem' }}>
          <h4 style={{ fontSize: '0.95rem', fontWeight: 700, marginBottom: '0.5rem', color: 'var(--risk-safe)', display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
            <CheckCircle size={16} /> Checklist: What to Bring to Your Lawyer:
          </h4>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.35rem', fontSize: '0.85rem' }}>
            {brief.checklistForMeeting.map((item, idx) => (
              <li key={idx} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text-secondary)' }}>
                <span style={{ color: 'var(--risk-safe)', fontWeight: 700 }}>✓</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Action Buttons */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', paddingTop: '1rem', borderTop: '1px solid var(--border-subtle)' }}>
          <button className="icon-btn" onClick={handlePrint}>
            <Printer size={16} />
            <span>Print / Save PDF</span>
          </button>
          <button className="btn-primary" onClick={handleCopy}>
            {copied ? <Check size={16} /> : <Copy size={16} />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy Markdown'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
